name: On New Tag

on:
  push:
    tags:
      - '*'

jobs:
  show-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Describe tag
        run: git describe --tags --exact-match --long
